print('Application for Services: To be considered for acceptance as a client, you must complete this form and return it to the Entrepreneurial Legal Services Clinic. Acceptance as a client of the UMKC Entrepreneurial Legal Services Clinic is not guaranteed, and is ultimately based upon available of resources and time to provide services, absence of conflicts of interest, financial need of the client, and educational value for our students. What is your full name?')
clientName = input()
print('What is the date? (dd/mm/yyyy)')
date = input()
print('What is the name of the entity?')
companyName = input()
print('What is your mailing address')
clientAddress = input()
print('What city do you live in?')
clientCity = input()
print('What state do you live in?')
clientState = input()
print('What zip code do you live in?')
clientZip = input()
print('What is your telephone number?')
clientPhone = input()
print('What is your email address? By providing your email address you are giving the Entrepreneurial Legal Services Clinic express permission to contact you via email with matters regarding your business and to contact you regarding other information that may be of interest to you. If you do not want the Entrepreneurial Legal Services Clinic type N/A')
clientEmail = input()
print('Applicants for services are hereby notified that the University of Missouri-Kansas City and the Entrepreneurial Legal Services Clinic do not discriminate on the basis of race, color, creed, sex, sexual orientation, age, national origin, disability or Vietnam era veterans status in admission or access to, or treatment or employment in, its programs and activities. Financial Information (required for means testing): What is your total expected income for this year?')
expectedAnnualIncome = input()
print('What was your total expected income for last year?')
pastAnnualIncome = input()
print('How much available capital do you have to spend for your entity?')
availableCapital = input()
print('Are you currently employed?')
clientEmployment = input()
if str(clientEmployment) == 'yes':                                #I'm not sure if these next few lines are properly formatted
    print('If so, where?')
    employmentLocation = input()
else:
    print('Demographic Information. This information is collected for demographic purposes only; it is anonymous and does not affect your acceptance as a client. What is your race?')

print('Demographic Information. This information is collected for demographic purposes only; it is anonymous and does not affect your acceptance as a client. What is your race?')
clientRace = input()
print('What is your gender?')
clientGender = input()
print('What is your marital status?')
clientMaritalStatus = input()
print('What is your highest level of education?')
clientEducation = input()

print('Required for conflicts check List any person or company, if any, who may have a claim against you or your business. If none, type n/a')
clientClaimants = input()
print('Are you currently a student at the University of Missouri at Kansas City or any other U- System campus?')
clientUMKCStudent = input()
print('Do you currently have or expect to have any contracts, employment, or other business relationship with the University of Missouri-Kansas City or any other campus, office or operation of the University of Missouri System?')
clientUMKCContracts = input()
print('Briefly state your legal question or problem/type of legal advice sought. If unsure, type n/a')
legalAdivceSought = input()
print('Please list any deadlines under which you are operating (court dates, etc. if any). If none, type n/a')
clientDeadlines = input()
print('I hereby state the above information is true to the best of my knowledge, and give permission to the Entrepreneurial Legal Services Clinic to check for potential conflicts of interests between myself and affiliates, and with current and former clients of the clinic, clients of firms at which students may be working, UMKC ,and the University of Missouri. I further confirm that I understand that work in the Entrepreneurial Legal Services Clinic is performed by law students under the supervision of licensed attorneys and therefore I may experience a delay due to the work being completed by said students. Type your signature in the following box to confirm that you are comfortable with the preceding obligations.')
clientSignature = input()
print('Type the date in the following box to confirm that you are comfortable with the preceding obligations')
clientDate = input()


# [Client Intake Form](http://www1.law.umkc.edu/clinics/els/application.pdf)
